const items=[
['Decawork','Product Hunt · Aug 24 #2','Agent Control Plane','IT 统一接管 company-owned Agent 的 access、oversight、retirement。','https://www.producthunt.com/products/decawork'],
['Agnost AI','Product Hunt · Aug 25 #3','Production Agent Assurance','从真实生产对话发现 eval 未覆盖的失败，再转成 eval 与修复。','https://www.producthunt.com/products/agnost-ai'],
['Navigara','Product Hunt · Aug 24 #4','AI FinOps / Outcome Attribution','把 AI coding spend 映射到 roadmap、capacity gain 与 maintenance burn。','https://www.producthunt.com/products/navigara'],
['Traccia','Product Hunt · Aug 27','Vendor-neutral Agent Control Plane','统一 observe、evaluate、policy/runtime control 与 audit trail。','https://www.producthunt.com/products/traccia'],
['GitNexus','Product Hunt · Aug 27 #8','Code Knowledge Graph','deterministic code graph，通过 MCP 给 Agent caller/import/impact context。','https://www.producthunt.com/products/gitnexus-akon-labs'],
['Lenz','Product Hunt · Aug 27 #3','Independent Verification','独立来源 + multi-model review 的事实验证 API/MCP。','https://www.producthunt.com/products/lenz-2'],
['Flare','Product Hunt · Aug 25','Graph-first Agentic IDE','dependency graph、Agent write attribution、snapshot/diff/revert。','https://www.producthunt.com/products/flare-11'],
['OpenComputer','Product Hunt · Aug 26 #7','Durable Agent Runtime','真实 Linux session，支持 hibernate/resume 与 secret boundary。','https://www.producthunt.com/products/opencomputer'],
['Caddi','Product Hunt · Aug 28 #2','Teach-by-demonstration Agent','一次 screenshare 学业务流程，生成带 scoped permission/run log 的 Agent。','https://www.producthunt.com/products/caddi-3'],
['Firecrawl Developer Index','Product Hunt · Aug 28','External Developer Data Plane','70M+ GitHub README、issue、PR、docs 的 coding-agent 搜索入口。','https://www.producthunt.com/products/extract-by-firecrawl']
];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W35 · 8 月 24 日—8 月 30 日</div><h1>海外 AI 产品周报：Control Plane 正式成类，Verification 进入独立 Assurance</h1><p className="lead">生产 Agent 的两条基础链开始清晰：Control Chain 决定它能不能做，Assurance Chain 独立证明它做对没有。</p><h2>Top 3 推荐</h2><ol><li><strong>Decawork / Traccia</strong>：连续六周的治理信号终于以 Agent Control Plane 这个名字直接产品化。</li><li><strong>Agnost AI / Lenz</strong>：Verification 从执行测试扩大到生产失败发现和独立事实复核。</li><li><strong>GitNexus</strong>：code context 进入 deterministic graph 阶段，并与 Flare、Firecrawl Developer Index 一起推动 Context 从 Memory 分化成专业 Data Plane。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>Agent Control Plane：连续第六周升温</strong><p>W30 secret isolation → W31 Skill/Eval/data authorization → W32 gateway/approval/recovery → W33 sandbox/action gate → W34 endpoint/repo/employee agent → W35 Decawork/Traccia 直接使用 Agent Control Plane 这个类别名。判断升级：它已是生产 Agent 的基础设施层。</p></div><div className="signal-box"><strong>Verification：升级为 Independent Assurance / Evidence Gate</strong><p>Agnost 做 production failure discovery；Lenz 做独立事实复核；PromptBrake 做 AI release assurance；Terminal-Bench-Science 用真实科研 workflow + deterministic verifier。共同原则是 generator 不能自己给自己打分。</p></div><div className="signal-box"><strong>Context：Shared Agent Data Plane 开始专业分层</strong><p>GitNexus 做 code graph，Flare 做 dependency/change graph，Firecrawl Developer Index 做 external developer artifact index。Memory 降为子能力，结构、来源、freshness 与 lineage 更重要。</p></div><div className="signal-box"><strong>FinOps：重新升温</strong><p>Navigara 把 AI spend 绑定 roadmap item、capacity gain 与 maintenance burn；Diet Claude / TokenPulse 补 usage visibility。高价值方向是 cost per accepted outcome。</p></div><div className="signal-box"><strong>首次信号：Teach-by-demonstration</strong><p>Caddi 通过一次 screenshare 学流程并生成 production agent。继续观察 Demonstration → Review → Skill/Spec 是否形成稳定范式。</p></div><div className="signal-box"><strong>未升级 / 回看</strong><p>Persistent Specification 没有第二个强样本；Agent Commerce 因 Purchase API by Agentcard 回到 watchlist，但仍缺身份、退款、争议闭环；Browser Execution 继续作为通用 adapter。</p></div><h2>本周 Top 10</h2>{items.map((x,i)=><section key={x[0]}><h3>{i+1}. {x[0]}</h3><p><strong>来源：</strong><a href={x[4]} target="_blank" rel="noreferrer">{x[1]}</a>　<strong>类别：</strong>{x[2]}</p><p>{x[3]}</p></section>)}<h2>下周继续观察</h2><ul><li>Control Plane 是否出现统一 capability / policy / run schema。</li><li>Independent Assurance 是否形成 evidence schema、release gate protocol 或 verifier API。</li><li>Code graph 是否成为 coding-agent 默认 context primitive。</li><li>FinOps 是否出现更多 cost-per-accepted-change 产品。</li><li>Teach-by-demonstration 是否出现第二、第三个实现。</li><li>Agent Commerce 是否补齐身份、退款、争议与责任闭环。</li></ul></article></main>}