const items=[
{slug:'onecli',name:'OneCLI',source:'OneCLI / GitHub / YC',url:'https://onecli.sh/',category:'Agent Security / Developer Infrastructure',signal:'2.5K+ Stars、30 万+下载、YC S26，跨产品发布、GitHub 与 YC 重复出现。',desc:'真实密钥在网络层按规则注入，Agent 只持有占位凭据。',why:'Agent 开始操作 GitHub、云平台、数据库和支付后，凭据隔离正在变成基础设施。',learn:'Agent 安全应从不让模型接触秘密开始，而不是只依赖 Prompt 和确认弹窗。',china:'接入阿里云 KMS、腾讯云 KMS、Vault，服务企业 Coding Agent 与 MCP。',write:'值得写：别把 API Key 交给 Agent。'},
{slug:'bento',name:'Bento',source:'Show HN',url:'https://bento.page/',category:'Local-first Productivity',signal:'Show HN 高讨论，产品已经可以直接下载使用。',desc:'一个 HTML 文件同时承担文档、编辑器、播放器和数据载体。',why:'它不是 AI 生成 PPT 的包装，而是重新定义文件与软件的边界。',learn:'文件可以重新成为软件交付单位；Local-first 也能降低协作和兼容成本。',china:'离线课件、投标演示、交互式报告和 AI 生成后可继续编辑的交付物。',write:'强烈值得写。'},
{slug:'ai-toolbox',name:'AI Toolbox',source:'Indie Hackers',url:'https://www.indiehackers.com/stories',category:'Browser Extension / Indie SaaS',signal:'创始人披露 35,000+ 活跃用户、五位数 MRR、4.5/5 评分，基础设施约 45 美元/月。',desc:'为 ChatGPT、Claude、Gemini、Grok 增加跨平台搜索、文件夹、书签和导出。',why:'这是本周最完整的独立开发商业案例：从真实投诉切入，借平台分发，用本地索引压低成本。',learn:'从重复投诉找需求；平台依赖可以换取低成本分发，但核心数据边界要留在自己手中。',china:'豆包、Kimi、DeepSeek、通义与 ChatGPT 的跨平台会话管理。',write:'强烈值得写，Creator Story 完整。'},
{slug:'cartai',name:'CartAI',source:'Product Hunt #2',url:'https://www.producthunt.com/products/cartai',category:'Agent Commerce',signal:'约 470 points、1K followers，讨论集中在授权、重复扣款、售后和责任边界。',desc:'让 Agent 在真实商家页面完成结账、支付和订单确认。',why:'它补上了 Agent 从研究到真实交易之间最难的一段。',learn:'交易闭环依赖明确授权、最终状态确认、可追踪订单和失败安全。',china:'微信支付、支付宝、小程序和本地生活代理购买层。',write:'值得写。'},
{slug:'palmier-pro',name:'Palmier Pro',source:'Show HN / GitHub',url:'https://github.com/palmier-io/palmier-pro',category:'AI Video Editor / MCP',signal:'12K+ Stars、897 forks、持续高频发布。',desc:'Claude、Codex、Cursor 通过 MCP 操作同一条真实视频时间线。',why:'它不是生成一个无法继续修改的黑盒视频，而是让 Agent 进入专业编辑状态。',learn:'专业 Agent 应操作可编辑、可撤销、可交接的真实项目对象。',china:'短剧、课程、广告和舞台大屏制作，可接国内视频模型。',write:'强烈值得写。'},
{slug:'migma-ai',name:'Migma AI',source:'Product Hunt #2',url:'https://www.producthunt.com/products/migma-ai',category:'Email Marketing / Domain DSL',signal:'约 497 points、2.8K followers；两兄弟团队完成六位数 pre-seed。',desc:'模型生成自研邮件 DSL Zinn，再编译为兼容不同客户端的邮件。',why:'专用 DSL 把模型随机性限制在可验证结构内。',learn:'复杂输出需要领域中间语言、验证和编译，而不是自由生成最终格式。',china:'公众号、短信、企微私域和电商营销 Campaign DSL。',write:'强烈值得写，偏产品架构。'},
{slug:'codealmanac',name:'CodeAlmanac',source:'Show HN / PyPI',url:'https://www.codealmanac.com/',category:'Coding Context / Project Memory',signal:'官网、PyPI、GitHub 持续更新，产品从一次性生成走向 ingest、garden、sync。',desc:'把 Coding Agent 会话沉淀为 Repo 内可维护的 Markdown Wiki。',why:'代码说明现在是什么，但 Agent 对话保存了大量为什么这样做。',learn:'项目记忆的关键是来源、去重、过期清理和 Git Review。',china:'GitLab/Gitee、TAPD、飞书需求和项目文档的上下文层。',write:'强烈值得写。'},
{slug:'brolly',name:'Brolly',source:'Show HN',url:'https://brolly.sh/',category:'Consumer Utility',signal:'HN 200+ points、70+ comments。',desc:'无账号、无 App 的高密度纯文本天气站。',why:'没有账户、推送和 AI 总结，仍靠速度、信息密度和可分享状态获得关注。',learn:'消费产品不一定要复杂化，清晰信息架构本身就是体验。',china:'花粉、空气质量、徒步、跑步和钓鱼垂直天气。',write:'值得写。'},
{slug:'did-they-ghost-you',name:'Did They Ghost You?',source:'Hacker News',url:'https://didtheyghostyou.com/',category:'Career Community',signal:'HN 高讨论，并迅速建立审核、申诉和纠错规则。',desc:'众包记录面试后失联和良好沟通的企业。',why:'它击中了强烈情绪，也暴露了社区声誉产品的治理难题。',learn:'核心是证据、审核、申诉和正反两类信号，不是排行榜。',china:'招聘流程透明度与求职 Agent 状态跟踪。',write:'值得写，与 Career Agent 方向直接相关。'},
{slug:'touchgrass',name:'TouchGrass',source:'Product Hunt #1',url:'https://touchgrass.land/',category:'Mac Utility / Local-first',signal:'约 392 points、535 followers，一次性 3.99 美元。',desc:'根据会议、媒体和离开电脑状态选择合适时机提醒休息。',why:'成熟品类仍有机会，关键可能不是增加功能，而是减少错误打扰。',learn:'提醒类产品的核心是时机，而不是更多通知。',china:'程序员、长任务 Agent 和久坐人群的本地状态工具。',write:'适合独立产品案例。'}
];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W30 · 7 月 20—26 日</div><h1>海外 AI 产品周报：Coding Agent 周边开始形成独立产品层</h1><p className="lead">首期以本周连续日报为历史基线。重点不是重新排榜，而是识别重复出现、同类集中爆发、首次形成、升温、降温和退出观察。</p><h2>Top 3 推荐</h2><ol><li><strong>OneCLI</strong>：Agent 凭据隔离从附加安全能力变成基础设施。</li><li><strong>Bento</strong>：一个 HTML 文件同时是文档、编辑器、播放器和数据载体。</li><li><strong>AI Toolbox</strong>：两人团队、35,000+ 活跃用户、五位数 MRR，商业信号最完整。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>同类集中爆发：Coding Agent 周边基础设施</strong><p>OneCLI、Kastra、Pushary、Heard、Openbase、Capsomnia、Claude-thermos、Remux、Palmier Pro、CodeAlmanac 在一周内连续出现。竞争从模型写代码能力转向凭据、权限、监督、状态、缓存、持续运行和项目上下文。</p></div><div className="signal-box"><strong>持续升温：Enterprise Context / Memory</strong><p>CodeAlmanac、Moxie Docs、Fluree AI、PromptQL、Second Brain 的共同变化是强调来源、权限、更新、冲突、删除、Git Review 和确定性查询。</p></div><div className="signal-box"><strong>首次形成：Agent 值守与注意力管理</strong><p>Pushary、Heard、Openbase、Capsomnia 集中解决长任务和多 Agent 并行之后的人类注意力问题。</p></div><div className="signal-box"><strong>出现分化：AI 视频</strong><p>单次生成型产品继续同质化；Palmier Pro、Buzzy 这类保留时间线、角色、场景和项目状态的工具获得更强持续信号。</p></div><div className="signal-box"><strong>降温与退出核心观察</strong><p>通用 AI Wrapper 缺少新的技术和商业信号。ditto.site、Manifest 有强单日讨论，但未形成跨来源连续验证，暂时只留在观察名单。</p></div><h2>本周 Top 10</h2>{items.map((x,i)=><section id={x.slug} key={x.slug}><h3>{i+1}. {x.name}</h3><p><strong>来源：</strong><a href={x.url} target="_blank">{x.source}</a>　<strong>类别：</strong>{x.category}</p><p><strong>产品：</strong>{x.desc}</p><p><strong>为什么值得关注：</strong>{x.why}</p><p><strong>发布与讨论信号：</strong>{x.signal}</p><p><strong>可以学什么：</strong>{x.learn}</p><p><strong>中国机会：</strong>{x.china}</p><p><strong>是否值得写：</strong>{x.write}</p></section>)}<h2>历史对比</h2><div className="signal-box"><strong>跨来源重复出现</strong><ul><li>OneCLI：产品发布、GitHub、YC 三类信号同时成立。</li><li>Palmier Pro：HN 讨论与 GitHub 持续增长同时存在。</li><li>CodeAlmanac：从早期 CLI 到 PyPI 持续发布，产品面仍在演进。</li></ul></div><div className="signal-box"><strong>连续出现的问题</strong><ul><li>Agent 如何安全获取凭据和权限。</li><li>人如何监督长任务和并行 Agent。</li><li>Coding Agent 会话如何沉淀为可维护的项目上下文。</li><li>生成内容如何落到可继续编辑的真实对象。</li></ul></div><h2>下周继续观察</h2><ul><li>OneCLI 是否出现企业客户、默认集成或安全审计信号。</li><li>CodeAlmanac 是否走向团队协作，同时保留本地与 Git Review。</li><li>Agent 值守工具是否形成留存，以及高风险审批是否有足够上下文。</li><li>Agent Commerce 是否出现退款、售后、争议处理和订单身份标准。</li><li>AI 视频是否继续向真实时间线和项目状态迁移。</li></ul></article></main>}