const items=[
{slug:'bento',name:'Bento',source:'Show HN',category:'Local-first / Presentation / Open Source',signal:'约 633 points、147 comments；本周讨论度最高之一。',desc:'把幻灯片编辑器、播放、打印、保存和实时协作封装进一个约 560KB 的 HTML 文件。无需账号、安装或云端数据库。',why:'它重新证明“文件即应用”仍然成立，也反映了用户对复杂云 SaaS 的疲惫。',learn:'单文件交付、开放格式和离线能力，本身就能形成产品差异。',china:'适合培训课件、投标演示、交互式报告和 AI 生成的可编辑交付物。',write:'★★★★★ 本周最值得写。'},
{slug:'onecli',name:'OneCLI',source:'Show HN / GitHub',category:'Agent Security / Credential Gateway',signal:'HN 强讨论；GitHub 约 2.6K Stars。',desc:'Agent 只持有占位符，真实密钥由网关根据目标 Host 与 Path 临时解密并注入，Agent 始终看不到 Secret。',why:'Agent 开始操作 GitHub、云平台、数据库和支付后，环境变量已经不是足够安全的凭据边界。',learn:'Agent 身份、凭据、授权和审计应分层；Secret 不应进入模型上下文。',china:'可连接阿里云 KMS、腾讯云 KMS、Vault 与企业内部 Coding Agent。',write:'★★★★★ 强烈值得。'},
{slug:'codealmanac',name:'CodeAlmanac',source:'Show HN / GitHub',category:'Coding Agent Memory / Project Wiki',signal:'约 43 points、15 comments；GitHub 约 551 Stars。',desc:'读取本地 Codex、Claude Code 对话，把架构决策、历史故障和跨文件约束整理成 Repo 内的 Markdown Wiki。',why:'代码说明“现在是什么”，Agent 对话里却保存了大量“为什么这样做”，而这些信息通常在任务结束后消失。',learn:'长期记忆的重点不是自动总结，而是筛选、来源、Git Review 与定期清理。',china:'可结合 GitLab/Gitee、TAPD、飞书需求与企业代码库，形成项目记忆层。',write:'★★★★★ 强烈值得。'},
{slug:'migma',name:'Migma AI',source:'Product Hunt',category:'Email Marketing / Vertical Agent',signal:'PH 日榜前列，约 373 points、2.6K followers。',desc:'根据品牌、受众和历史效果生成邮件活动，但模型不直接输出 HTML，而是先生成团队设计的邮件中间语言 Zinn。',why:'专用 DSL 把模型随机性限制在可验证结构内，再解决 Outlook、暗色模式与 Gmail 截断。',learn:'复杂领域输出更适合“意图 → DSL → 验证 → 编译”，而不是自由生成最终产物。',china:'可扩展到公众号、企微私域、短信和电商营销的统一 Campaign DSL。',write:'★★★★★ 强烈值得。'},
{slug:'palmier',name:'Palmier Pro',source:'Show HN / GitHub',category:'AI Video Editor / MCP',signal:'HN 约 118 points；GitHub 约 11K Stars。',desc:'原生 macOS 视频编辑器，让 Claude、Codex、Cursor 通过 MCP 操作同一个真实时间线。',why:'它不是生成一个无法继续修改的黑盒视频，而是让 Agent 进入专业编辑状态。',learn:'AI 创作产品的关键是共享对象、可撤销状态和人与 Agent 的接力，而不是一次生成。',china:'适合短剧、课程、访谈和舞台大屏制作，可接国内视频模型。',write:'★★★★★ 强烈值得。'},
{slug:'aitoolbox',name:'AI Toolbox',source:'Indie Hackers',category:'Browser Extension / Productivity',signal:'创始人披露 35,000+ 活跃用户、五位数 MRR、月基础设施约 45 美元。',desc:'为 ChatGPT、Claude、Gemini 等增加跨平台全文搜索、文件夹、书签和批量导出。',why:'两人团队从 Reddit 与官方论坛的真实抱怨出发，用极简架构吃到平台分发。',learn:'平台依赖不是绝对禁区，而是用稳定性风险换低成本分发；关键是保留数据边界。',china:'豆包、Kimi、DeepSeek、通义与 ChatGPT 的跨平台会话搜索层。',write:'★★★★★ 最适合独立开发者故事。'},
{slug:'fluree',name:'Fluree AI',source:'Product Hunt',category:'Enterprise Context / Knowledge Graph',signal:'PH 日榜前列，约 286 points、721 followers。',desc:'把数据库、文档和 SaaS 数据组织成带来源、权限和审计的知识图谱，供 Agent 结构化查询。',why:'企业 Agent 的根本矛盾通常不是检索不到，而是多系统数据冲突、权限不同和来源不清。',learn:'企业上下文层必须同时处理数据、关系、来源、权限、查询和审计。',china:'适合制造、金融、政企和大型集团的统一 Agent 数据层。',write:'★★★★☆ 值得深挖。'},
{slug:'kastra',name:'Kastra',source:'Product Hunt',category:'Agent Authorization / Runtime Security',signal:'PH 日榜约 #4，316 points、623 followers。',desc:'在 Agent 的每次 Tool Call 执行前做确定性策略检查，下游嵌套动作也重新授权。',why:'Prompt 和确认弹窗不是安全边界，真正的权限应由模型之外的独立系统决定。',learn:'Agent 提出动作，授权层决定能否执行，执行结果必须可审计。',china:'企业内部 MCP、数据库、文件与生产环境的统一授权控制面。',write:'★★★★☆ 值得写。'},
{slug:'brolly',name:'Brolly',source:'Show HN',category:'Consumer Utility / Weather',signal:'约 125 points、42 comments；公开统计约 2 万独立访问者。',desc:'纯文本天气网站，用字符图呈现七天天气、降雨、风力、空气质量和花粉，状态全部编码在 URL。',why:'没有 App、账号、推送和 AI 总结，依然靠速度、信息密度与可分享性获得关注。',learn:'消费工具不一定要复杂化；清晰信息架构本身就是体验。',china:'适合花粉、徒步、跑步、钓鱼和空气质量等垂直天气入口。',write:'★★★★☆ 适合产品设计案例。'},
{slug:'honorbox',name:'HonorBox',source:'Product Hunt / GitHub',category:'Micro SaaS / Developer Commerce',signal:'约 100 points；约 350 行免费引擎，MIT License。',desc:'GitHub Pages 承载商店，Stripe Payment Link 收款，GitHub Action 自动邀请买家进入私有 Repo。',why:'它把现有基础设施拼成最小闭环，真正工程价值集中在支付延迟、邀请失败等异常路径。',learn:'小产品的壁垒经常不是 Happy Path，而是可靠处理静默失败。',china:'可面向源码、模板、Skill 和私有 Repo 销售，支付替换为微信或支付宝。',write:'★★★★☆ 小而硬的案例。'}];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W30 · 7月20日—7月26日</div><h1>海外 AI 产品周报：Agent 的外围基础设施开始成形</h1><p className="lead">本周不是某一个模型突然变强，而是围绕 Agent 的记忆、安全、值守、编辑状态和企业上下文同时出现了一批产品。与此前零散工具相比，它们开始形成可以被独立命名的产品层。</p><div><span className="tag">Agent Security</span><span className="tag">Coding Agent</span><span className="tag">Enterprise Context</span><span className="tag">Local-first</span><span className="tag">Domain DSL</span></div><h2>Top 3 推荐</h2><ol><li><strong>Bento</strong>：单文件软件重新获得生命力，技术实现、讨论和产品理念都完整。</li><li><strong>OneCLI</strong>：Agent 不该看到真实密钥，凭据隔离会成为企业 Agent 的基础设施。</li><li><strong>CodeAlmanac</strong>：Coding Agent 的历史对话开始被转化为可审阅、可清理的项目记忆。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>1. Coding Agent 的竞争从“写代码”转向“值守”</strong><p>此前关注模型与编辑器，本周 Heard、Pushary、Openbase、Remux 等连续出现。共同问题是：Agent 可以长时间并行工作，但人类无法持续盯着终端。语音播报、手机审批、远程接续和风险分级正在形成新的产品层。</p></div><div className="signal-box"><strong>2. Agent Security 连续出现，已不再是偶发需求</strong><p>Kastra 处理每次 Tool Call 的确定性授权，OneCLI 处理真实凭据不进入 Agent Context。两者分别补上“能不能做”和“拿什么身份做”，说明安全正在从产品功能变成独立控制面。</p></div><div className="signal-box"><strong>3. 自由生成开始让位于专用中间层</strong><p>Migma 使用邮件 DSL，Manifest 把网页转换为 Action Schema，ditto.site 采用确定性页面捕获。它们都在减少模型直接生成最终产物的范围，把 LLM 放在意图理解与结构生成层。</p></div><div className="signal-box"><strong>4. Memory 正在升级为 Enterprise Context</strong><p>CodeAlmanac 关注项目决策，Fluree 关注来源、关系、权限和审计，Glean 开始强调 Enterprise Memory。趋势重点已从“能否召回”转向“是否可信、是否新鲜、谁有权看、为什么得到这个答案”。</p></div><div className="signal-box"><strong>5. AI Video 出现明显分化</strong><p>通用生成产品仍多，但更值得关注的产品已转向真实时间线、角色实体、镜头状态和可继续编辑。Palmier Pro 与 Buzzy 代表的不是更强模型，而是更完整的创作工作流。</p></div><h2>本周 Top 10</h2>{items.map((x,i)=><section id={x.slug} key={x.slug}><h3>{i+1}. {x.name}</h3><p><strong>来源：</strong>{x.source}　<strong>类别：</strong>{x.category}</p><p><strong>产品：</strong>{x.desc}</p><p><strong>为什么值得关注：</strong>{x.why}</p><p><strong>发布与讨论信号：</strong>{x.signal}</p><p><strong>可以学什么：</strong>{x.learn}</p><p><strong>中国机会：</strong>{x.china}</p><p><strong>是否值得写：</strong>{x.write}</p></section>)}<h2>本周长期判断</h2><blockquote><strong>Agent 产品的下一阶段，不只是让 Agent 更能干，而是建立模型之外的控制层、状态层和可信上下文层。</strong></blockquote><p>本周最明确的共同点是：真正有价值的产品不再只包裹模型输出，而是在解决长期运行中的现实问题——凭据、权限、记忆、回滚、编辑状态、异常路径和人的注意力。这个趋势若连续三到四周保持，将意味着 Agent Infra 已从技术组件进入独立产品爆发期。</p><h2>下周继续观察</h2><ul><li>Agent Security 是否继续出现新产品，并从开发者工具进入企业采购。</li><li>Coding Agent 手机值守是否出现风险分级、Diff 审阅和成本控制。</li><li>Enterprise Memory 是否进一步被“Context / Graph / Provenance”取代。</li><li>专用 DSL 是否扩展到合同、报表、演示和业务工作流。</li><li>AI Video 产品是否继续从模型聚合转向专业编辑状态。</li></ul></article></main>}
