const items=[
['Mastra Factory','Product Hunt · Sep 9 #1','Agent-native SDLC / Software Factory','把 issue、persistent agents、repo workspaces、planning、implementation、PR review、release、docs、production monitoring 收进统一环境。','https://www.producthunt.com/products/mastra'],
['Harden','Product Hunt · Sep 8 #2','Runtime Security','coding-agent tool call 执行前，结合用户请求和 session context 做本地安全判断。','https://www.producthunt.com/products/agent-integrity-foundation-aif'],
['easyspecs.ai','Product Hunt · Sep 11','Persistent Specification / Verification','从 codebase 生成 spec，并配 validators、Oracles、Rubrics，把 spec 变成 acceptance contract。','https://www.producthunt.com/products/easyspecs-ai'],
['PR Lens by Coldtea.ai','Product Hunt · Sep 7 #1','Architecture Review','为 codebase/PR 生成动态 architecture 与 data-flow 图，降低 AI-generated diff 的 review 负担。','https://www.producthunt.com/products/coldtea'],
['AI Observability by OpenObserve','Product Hunt · Sep 10 #2','Agent Observability','OTel-native 串起 model/tool/service/datastore/session，同时观察 latency、cost、quality、failure 与 online eval。','https://www.producthunt.com/products/openobserve'],
['Replay QA Security Scan','Product Hunt · Sep 10','Executable Security Verification','对 live/localhost app 做真实 penetration test，返回漏洞、evidence 与 fix suggestion。','https://www.producthunt.com/products/replayio'],
['QApilot MCP for Android','Product Hunt · Sep 12 #3','Mobile Executable Verification','coding agent 驱动真实 Android 设备/模拟器，通过后生成 Gherkin 与 replayable test case。','https://www.producthunt.com/products/qapilot'],
['Relaticle','Product Hunt · This week','Approval-gated Writes','Agent-first CRM，每个 write 都先成为明确 proposal，再按 record 批准。','https://www.producthunt.com/products/relaticle'],
['Thousand','Product Hunt · Sep 10 #10','Shared Agent Data Plane','Git-backed Markdown + folder-level ACL，让人和 Agent 都只看到显式授权 context。','https://www.producthunt.com/products/thousand'],
['Agent Reliability Toolkit','Indie Hackers · Sep 10','Repeated-run Reliability','同一 Agent 重复运行 50/100 次，观察 pass/fail、failure、latency 与 regression。','https://www.indiehackers.com/product/agent-reliability-toolkit'],
['Mireye','Launch HN · Sep','Physical-world Agent Data Plane','为地点提供 cited facts、enrichment、tools、signals，并明确区分 ok/absent/failed。','https://news.ycombinator.com/item?id=49552616'],
['Viaduct','Show HN · Sep 13','Architecture Change Set','面向 AI coding agents 的 architecture change sets；目前验证弱，但与本周 review/spec 方向一致。','https://news.ycombinator.com/item?id=49662336']
];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W37 · 9 月 7—13 日</div><h1>海外 AI 产品周报：Coding Agent 开始长成 Software Factory</h1><p className="lead">本周真正的变化不是代码生成再快一点，而是工作系统、权限系统和证据系统开始围绕 Agent 形成完整生产闭环。</p><h2>Top 3 推荐</h2><ol><li><strong>Mastra Factory</strong>：Agent-native SDLC 从零散工具升级成 Agentic Software Factory，persistent agents 开始长期占据 issue→release 的完整交付流程。</li><li><strong>Harden / Relaticle / StareBrain</strong>：Control Plane 连续第八周升温，授权粒度进入 per-action authority——执行的那一刻仍要确认对象、参数和时间窗口有效。</li><li><strong>EasySpecs / PR Lens / Replay / QApilot / OpenObserve</strong>：Evidence-native requirement 进一步形成贯穿 Spec、Review、Test、Security、Production 的 Evidence Spine。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>Agent-native SDLC → Agentic Software Factory</strong><p>W34—W36 的 Git forge、worktree、review、debug、learning 都是部件；Mastra Factory 开始把长期 work state、phase gate、handoff、release 与 production feedback 收到同一系统里。</p></div><div className="signal-box"><strong>Control Plane：连续第八周升温</strong><p>W36 已确认 policy 必须位于 execution path；W37 再推进到 per-action authority。静态“Agent 有权限”不够，真正执行前必须重新验证 actor、object、parameters、time window。</p></div><div className="signal-box"><strong>Persistent Specification：重新升温</strong><p>EasySpecs 把 spec 与 validators、Oracles、Rubrics 绑定。Spec 更可能成为 Agentic SDLC 的 machine-verifiable control artifact，而不是独立文档类别。</p></div><div className="signal-box"><strong>Evidence-native Requirement → Evidence Spine</strong><p>Spec/Oracle、Architecture Impact、Real-device Test、Security Evidence、Production Trace、Repeated-run Reliability 开始连成生命周期证据链。</p></div><div className="signal-box"><strong>FinOps：继续不作为一级趋势</strong><p>OpenObserve 把 cost 与 latency、quality、failure、online eval 放在同一 production observability surface，成本更像一组运行指标而非独立产品价值。</p></div><div className="signal-box"><strong>Data Plane：继续升温</strong><p>Thousand 强化 Context ACL；Mireye 把 Data Plane 首次明显延伸到 physical world，但目前只有一个强样本，先观察。</p></div><div className="signal-box"><strong>降温 / 退出</strong><p>Agent Behavior Learning 本周缺第三个直接样本；Capability Router 缺第二个 Monid 级实现；Teach-by-demonstration 连续两周无强样本，退出重点观察；MCP 继续作为 plumbing 扩散。</p></div><h2>本周 Top 12</h2>{items.map((x,i)=><section key={x[0]}><h3>{i+1}. {x[0]}</h3><p><strong>来源：</strong><a href={x[4]} target="_blank" rel="noreferrer">{x[1]}</a>　<strong>类别：</strong>{x[2]}</p><p>{x[3]}</p></section>)}<h2>下周继续观察</h2><ul><li>是否出现第二个完整 Agentic Software Factory。</li><li>Per-action authority 是否出现 capability lease、object scope、parameter constraints 的标准化实现。</li><li>Spec 是否成为 coding agent 与 verifier 共用的机器可执行 contract。</li><li>Evidence 是否出现统一 artifact / lineage，贯穿 issue、PR、test、production trace。</li><li>Agent Observability 是否继续吸收 Eval 与 FinOps。</li><li>Physical-world Agent Data Plane 是否出现第二个强样本。</li></ul></article></main>}