const items=[
{name:'Ito',source:'Product Hunt / Official',url:'https://www.ito.ai/',category:'Executable Code Review',desc:'在 PR 上启动隔离环境并实际运行受影响流程。',why:'Code Review 从静态判断推进到运行证据，验证层开始成为 coding agent 的独立基础设施。'},
{name:'Tines 3B',source:'Product Hunt / Tines',url:'https://www.tines.com/3b/',category:'Enterprise Agent Runtime',desc:'统一构建、运行和治理 Agent、App 与 Automation。',why:'sandbox、runtime secret injection、权限与审计把 Control Plane 落到真正可阻断的执行边界。'},
{name:'Xirp',source:'Product Hunt / Spotify',url:'https://backstage.io/',category:'Agentic Development Workspace',desc:'把 catalog context、skills、active AI sessions 与 docs 汇入统一工程工作面。',why:'Skills、Context 与 Workspace 正向组织级执行上下文合流。'},
{name:'Paritok',source:'Product Hunt #3',url:'https://www.producthunt.com/products/paritok',category:'Runtime FinOps / Context',desc:'本地压缩 coding agent 的 tools、files、outputs 与 stale history。',why:'FinOps 从事后账单进入一次 Agent Run 内的上下文分配与成本控制。'},
{name:'Kane CLI',source:'Product Hunt / TestMu AI',url:'https://www.testmuai.com/natural-language-browser-testing/',category:'Browser Verification',desc:'自然语言测试真实 Chrome，返回明确 pass/fail、视频和 trace。',why:'Coding Agent 的完成标准正在变成独立 verifier 的可审查 evidence。'},
{name:'oqoqo',source:'Product Hunt',url:'https://oqoqo.ai/',category:'Agent Evals / Benchmarks',desc:'在 production-like sandbox 重复运行真实 workflow 并比较结果。',why:'Generic Eval 会商品化，但真实环境、业务 rubric 和 release gate 正升温。'},
{name:'Dograh',source:'Product Hunt / GitHub',url:'https://www.dograh.com/',category:'Open-source Voice Agent Infra',desc:'开源、自托管的 Voice Agent stack，集成 telephony、语音模型、workflow、测试与 MCP。',why:'Voice Agent plumbing 正开源化，产品价值继续向领域流程、数据、质量与交付迁移。'},
{name:'Grok Bot',source:'Product Hunt / Public launch',url:'https://grok.com/',category:'Persistent Cloud Agent',desc:'长期云端电脑上的 AI teammate，可做多步工作、并行协作并在敏感节点 handoff。',why:'Agent 产品形态继续从聊天助手向可委派云端工作者演进。'},
{name:'BrowserAct Cloud',source:'Product Hunt / Show HN',url:'https://www.browseract.com/',category:'Browser Layer for Agents',desc:'可重复 browser bot，处理登录态、验证、人类接管与结构化输出。',why:'Browser use 正从能力 Demo 变成执行基础设施。'},
{name:'Cynative',source:'Show HN / GitHub',url:'https://github.com/cynative/cynative',category:'Least-privilege Infra Agent',desc:'只读云与 Kubernetes 分析，sandbox + action gate + fail-closed + verifier。',why:'把权限控制放在模型之外，是比安全提示词更可靠的 Agent Security 路径。'}
];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W33 · 8 月 10 日—8 月 16 日</div><h1>海外 AI 产品周报：Agent 开始从“会做”走向“能证明”</h1><p className="lead">本周最重要的变化不是又出现了更自主的 Agent，而是执行系统开始被要求证明两件事：这次动作是被允许的，结果也确实发生了。Control Plane 与 Evals 正同时向执行边界收敛。</p><h2>Top 3 推荐</h2><ol><li><strong>Ito</strong>：Code Review 从读 diff 走到实际运行受影响流程并留下 evidence。</li><li><strong>Tines 3B</strong>：用隔离执行、runtime secret injection、权限与审计把 Agent 治理落到硬边界。</li><li><strong>Xirp</strong>：Spotify 把组织 context、skills、active sessions 与 docs 合入统一 Agentic Development Workspace。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>连续四周升温：Agent Control Plane → Least-privilege Execution</strong><p>W30 从凭据与值守开始，W31 加入版本、Eval 和授权，W32 进入 Gateway、审批和恢复，本周 Tines 3B、Cynative 进一步落到 sandbox、secret proxy、read-only action gate、fail-closed policy 与 audit evidence。Control Plane 越来越不像一个 Dashboard，而是一组模型无法绕过的执行规则。</p></div><div className="signal-box"><strong>判断修正：Generic Eval 商品化，Executable Verification 升温</strong><p>基础 Trace/Score 继续变成标配，但 Ito、Kane CLI、oqoqo 同周把验证推进到真实或可复现环境：执行任务、留下 pass/fail、视频、trace 和 diff。新价值不是更多评分，而是独立可执行验收。</p></div><div className="signal-box"><strong>持续升温：Context 进入 Runtime Economics</strong><p>CodeAlmanac → MemoryCustodian → Hexis → Xirp 连续验证 Context 的来源、版本、权限与组织 ownership；Paritok 又补上成本维度。未来 Context Engine 同时要决定读什么、读多少以及如何回源。</p></div><div className="signal-box"><strong>首次形成：Runtime FinOps</strong><p>W31 是统计花费，W32 是成本连接业务结果，W33 开始在 Run 内主动减少无效上下文。最终计量单位更可能是 accepted outcome，而不是 token。</p></div><div className="signal-box"><strong>同类集中：Open Agent Infrastructure 商品化加速</strong><p>Dograh、BetterClaw、Freebuff 等继续压低基础 Agent stack 的门槛。单纯“搭一个 Agent”的溢价会下降，价值向领域数据、可靠性、治理、集成与结果责任迁移。</p></div><div className="signal-box"><strong>降温与退出</strong><p>W32 的 Autonomous Software Maintenance 本周没有同级连续信号，退回长期观察；Agent Commerce 仍缺订单身份、退款与争议处理的新证据，再次退出核心趋势。Relay.app 停止服务也提示通用 no-code Agent workflow 的商业耐久性偏弱。</p></div><h2>本周 Top 10</h2>{items.map((x,i)=><section key={x.name}><h3>{i+1}. {x.name}</h3><p><strong>来源：</strong><a href={x.url} target="_blank" rel="noreferrer">{x.source}</a>　<strong>类别：</strong>{x.category}</p><p><strong>产品：</strong>{x.desc}</p><p><strong>为什么值得关注：</strong>{x.why}</p></section>)}<h2>历史判断变化</h2><ul><li><strong>Agent Control Plane：</strong>连续四周增强，开始从“看得见”走到“权限真正不可越过”。</li><li><strong>Evaluation：</strong>不是整体降温，而是 Generic Eval 商品化、Executable Verification 升温。</li><li><strong>Context：</strong>从知识管理演进到组织 Workspace，并进入 runtime cost 与 session longevity。</li><li><strong>FinOps：</strong>从账单统计走到结果关联，再走到 Run 内主动优化。</li><li><strong>Autonomous Maintenance：</strong>暂不升级为主趋势，等待真实回归率、回滚率和人工接管成本。</li></ul><h2>下周继续观察</h2><ul><li>Executable Verification 是否扩展到客服、运营和企业 workflow。</li><li>Tines 3B 类平台是否形成标准化 run evidence / capability manifest。</li><li>Xirp 是否把组织 context 与具体 run、ownership 和变更历史真正绑定。</li><li>FinOps 是否从 token reduction 走向 cost-per-accepted-outcome。</li><li>Persistent cloud agent 是否公开恢复、审批、凭据隔离与失败处理机制。</li></ul></article></main>}