const items=[
['Reflexio','Product Hunt · Sep 5 #2','Agent Behavioral Learning','把 correction、failure、success 转成可见、可测试、可逆的长期行为。','https://www.producthunt.com/products/reflexio-2'],
['Doberman','Indie Hackers / Product Hunt · Sep 1','Runtime Authorization','开源 local-first policy engine，在 shell/file/MCP action 执行前授权。','https://www.indiehackers.com/product/doberman'],
['Agent Builder by Airtop','Product Hunt · Sep 3 #2','Self-healing Automation','workflow 失败后自动调查、重建步骤，并用真实 test run 验证修复。','https://www.producthunt.com/products/airtop'],
['Monid','Product Hunt · Sep 2 #1','Agent Tool Router','一个 key 连接 1,800+ APIs，支持 runtime discovery、run 与 pay-per-tool。','https://www.producthunt.com/products/monid'],
['HyperProbe','Product Hunt · Sep 5','Production Debugging','向运行服务插入只读 probe 捕获未记录变量状态，无需 redeploy。','https://www.producthunt.com/products/hyperprobe'],
['Blume.codes','Product Hunt · Sep 3','Coding Agent Learning','从 coding sessions 提炼 repeated corrections → rules、workflows → skills。','https://www.producthunt.com/products/blume-codes'],
['Basedash AI Sources','Product Hunt · Sep 2','Evidence / Provenance UX','展示 answer 背后的 table、SQL/query、MCP source、row preview 等 receipts。','https://www.producthunt.com/products/basedash'],
['Aegisora 2.0','Indie Hackers · Sep 2','Execution Security','runtime policy 位于 execution path，每个 action allow/block/escalate 并保留审计生命周期。','https://www.indiehackers.com/post/we-built-aegisora-2-0-an-execution-security-layer-for-ai-agents-yKOXKHcLoMwSScpdeSzo'],
['GitWarren','Product Hunt · Sep 5','Local Agent Code Review','在 push 前审查 working tree change，以本地 PR-like UI 管理 AI review thread。','https://www.producthunt.com/products/gitwarren'],
['Almanac','Launch HN · Sep','Enterprise Knowledge','企业 company-knowledge agent；权限、source of truth 与 predictable behavior 是主要观察点。','https://news.ycombinator.com/item?id=49511007'],
['FrontierHarness Eval','Show HN · Sep','Agent Harness Evaluation','同模型跨不同 harness 比较 pass 与 cost，关注系统组合而非单模型 benchmark。','https://news.ycombinator.com/item?id=49538490']
];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W36 · 8 月 31 日—9 月 6 日</div><h1>海外 AI 产品周报：Agent 开始形成第三条 Learning Loop</h1><p className="lead">生产 Agent 不只需要 Control 与 Assurance。新的问题是：一次纠正、失败或成功，什么时候应该真正改变它未来的行为？</p><h2>Top 3 推荐</h2><ol><li><strong>Reflexio / Blume.codes</strong>：Agent Learning Loop 首次形成产品簇，运行反馈开始被提炼成可测试、可逆的 behavior、rules、skills。</li><li><strong>Doberman / Aegisora 2.0</strong>：Control Plane 进入 execution-path enforcement；policy 不再只出现在 Dashboard，而是在 action 发生前真正阻断。</li><li><strong>Airtop / HyperProbe / Basedash</strong>：Independent Assurance 从独立 verifier 变成产品内建的 Evidence-native requirement。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>没有同名连续上榜，但类别连续性更强</strong><p>W35 Top 10 与本周 Top 11 没有完全同名产品。Control Plane、Evidence、Data Plane、Agent-native SDLC 却继续由新团队独立重复验证。</p></div><div className="signal-box"><strong>首次形成：Agent Behavior Supply Chain</strong><p>Reflexio + Blume.codes 把 corrections/failures/successes 变成 future behavior。它不同于 Persistent Spec 和 Teach-by-demonstration，更接近从真实运行反馈生成候选规则，再经过 test / scope / promotion。</p></div><div className="signal-box"><strong>Control Plane：连续第七周升温</strong><p>W35 类别名称被市场确认；W36 Doberman/Aegisora 将 enforcement 下沉到 execution path。runtime allow/block 正变成开源基础能力，价值上移到 identity、policy distribution、exception、evidence、compliance。</p></div><div className="signal-box"><strong>Assurance：判断修正</strong><p>Airtop 的 real-run verify、HyperProbe 的 production evidence、Basedash 的 query receipts 说明 Assurance 不一定独立成一类 SaaS，更可能成为高风险 Agent 必备的 evidence surface + acceptance gate。</p></div><div className="signal-box"><strong>Agent-native SDLC：继续升温</strong><p>GitWarren、HyperProbe、Blume 把重心从执行推进到 pre-commit review、production debugging、session learning。</p></div><div className="signal-box"><strong>MCP：协议扩散，产品类别降温</strong><p>“支持 MCP”已经不构成差异。Monid 更值得看的是 capability discovery、routing、metering、payment。</p></div><div className="signal-box"><strong>降温 / 未升级</strong><p>AI FinOps 本周缺第二个强商业样本；Teach-by-demonstration 没有第二个直接实现；Agent Commerce 继续 watchlist；Generic No-code Workflow 仅因 Airtop 的 verify 闭环做判断微调。</p></div><h2>本周 Top 11</h2>{items.map((x,i)=><section key={x[0]}><h3>{i+1}. {x[0]}</h3><p><strong>来源：</strong><a href={x[4]} target="_blank" rel="noreferrer">{x[1]}</a>　<strong>类别：</strong>{x[2]}</p><p>{x[3]}</p></section>)}<h2>下周继续观察</h2><ul><li>是否出现第三个 Agent Learning / behavioral rule 产品。</li><li>Learning 是否形成 test、scope、promotion、rollback schema。</li><li>Control Plane 是否进入组织级 identity + policy distribution + evidence。</li><li>Evidence-native UX 是否扩展到非 coding 场景。</li><li>Agent-native SDLC 是否出现统一 change / evidence / review object。</li><li>Capability router 是否加入 permission、budget、reputation、SLA。</li></ul></article></main>}