const items=[
{name:'localskills.sh',source:'Product Hunt',url:'https://www.producthunt.com/products/localskills-sh',category:'Agent Skills / Governance',desc:'统一创建、安装和同步多种 Coding Agent 使用的 Skills 与 Rules。',why:'Skill 开始从个人配置变成需要版本、权限、来源和审计的团队资产。',signal:'本周发布；讨论集中在版本漂移、加载证明、权限和供应链治理。'},
{name:'Prefactor',source:'Product Hunt #1',url:'https://www.producthunt.com/products/prefactor',category:'Agent Evaluation',desc:'对生产中的每次 Agent Run 实时评分，发现质量回退和漂移。',why:'它把竞争从离线模型分数推进到线上质量回归。',signal:'7 月 28 日榜首，约 608 points、1.3K followers。'},
{name:'MarbleOS',source:'Show HN',url:'https://marbleos.com/demo',category:'Agent Workspace',desc:'用可见文件、工具、任务和输出组织 Agent 工作。',why:'复杂 Agent 产品需要可检查对象，而不是无限延长的 Chat UI。',signal:'Show HN 约 131 points、77 comments。'},
{name:'Prelint',source:'Product Hunt #1',url:'https://www.producthunt.com/products/prelint',category:'AI Code Review / Decision Governance',desc:'依据 ADR、产品文档和历史决策审查 PR。',why:'AI Code Review 的价值正在从语法问题转向组织决策是否被执行。',signal:'7 月 29 日榜首，约 612 points、1.1K followers。'},
{name:'Cekura',source:'Product Hunt #2',url:'https://www.producthunt.com/products/vocera',category:'Voice / Chat Agent QA',desc:'模拟大量场景，定位失败原因，修改配置并重新回归。',why:'自我改进必须有测试集、根因定位和回归验证。',signal:'7 月 28 日第二，约 411 points、2.3K followers。'},
{name:'MemoryCustodian',source:'Product Hunt',url:'https://www.producthunt.com/products/memorycustodian',category:'Repo-owned Context',desc:'把决策、约束和被否决方案保存为仓库内 Markdown，并按任务加载。',why:'长期记忆的关键是所有权、选择性加载、来源和可审查。',signal:'本周发布，约 189 followers、165 points。'},
{name:'Rivault',source:'Product Hunt',url:'https://www.producthunt.com/products/rivault',category:'Agent Data Authorization',desc:'Agent 请求敏感数据时由用户逐次授权，使用后重新隐藏。',why:'安全边界从凭据隔离扩展到最小数据暴露。',signal:'本周发布，约 101 followers、113 points。'},
{name:'MCP-Billing',source:'Product Hunt',url:'https://www.producthunt.com/products/mcp-billing',category:'MCP Infrastructure',desc:'为 MCP Server 提供 OAuth、密钥轮换、用量计费和限流。',why:'MCP 正从 Demo 接口进入身份、计费和运营基础设施阶段。',signal:'本周发布，约 117 followers、118 points。'},
{name:'DepthData',source:'Product Hunt #5',url:'https://www.producthunt.com/products/depthdata',category:'Enterprise AI FinOps',desc:'汇总企业多个 AI 工具的成本、采用率和验证质量。',why:'企业 AI 管理开始需要使用、成本和质量的统一账本。',signal:'7 月 31 日第五，约 173 points、248 followers。'},
{name:'TurboFieldfare',source:'Show HN / GitHub',url:'https://github.com/drumih/turbo-fieldfare',category:'Local Model Runtime',desc:'在 Apple Silicon 上以约 2GB 内存运行 Gemma 4 26B-A4B。',why:'本地模型机会取决于真实内存、延迟和部署门槛。',signal:'Show HN 约 904 points、340 comments。'}
];
export default function Weekly(){return <main><article className="report shell"><div className="eyebrow">2026-W31 · 7 月 27 日—8 月 2 日</div><h1>海外 AI 产品周报：Agent 基础设施开始形成控制面</h1><p className="lead">与上周相比，Coding Agent 周边没有降温，但焦点已从“让 Agent 能运行”转向“让团队能够治理、评测、审查和复现”。</p><h2>Top 3 推荐</h2><ol><li><strong>localskills.sh</strong>：Skill 开始成为有版本、权限、来源和审计要求的团队资产。</li><li><strong>Prefactor</strong>：把 Agent Evaluation 放进每次生产运行，竞争从模型分数转向线上质量回归。</li><li><strong>MarbleOS</strong>：用文件、任务、工具和输出构成可见工作区，代表 Agent 产品从 Chat-first 转向 Workspace-first。</li></ol><h2>与历史相比，本周发生了什么</h2><div className="signal-box"><strong>连续升温：Coding Agent 基础设施进入 Control Plane</strong><p>上周主要解决凭据、持续运行和远程监督；本周的 localskills.sh、Prefactor、Prelint、DepthData、Rivault 把重点推进到版本、评测、决策门禁、成本归因和数据授权。</p></div><div className="signal-box"><strong>判断得到验证：Memory 正在拆成 Context Lifecycle</strong><p>CodeAlmanac 强调 Repo-owned Markdown；本周的 MemoryCustodian、Greplica 等继续强调来源、选择性加载、更新和审查。单纯“记住更多”不是方向，能够维护和证明上下文才是。</p></div><div className="signal-box"><strong>首次形成：Agent Evaluation 与自我改进闭环</strong><p>Prefactor、Cekura、TraceLLM 覆盖运行追踪、质量评分、根因定位、修正和回归验证。没有回归验证的“自我改进”只是自动修改。</p></div><div className="signal-box"><strong>首次形成：Skill 供应链与 MCP 运营层</strong><p>localskills.sh 处理 Skill 的分发、版本和权限，MCP-Billing 处理 MCP 的身份、限流和计费。Skill 与 MCP 正从个人配置和 Demo 进入可运营资产。</p></div><div className="signal-box"><strong>持续演进：Agent 值守从通知转向可见工作区</strong><p>上周的产品主要解决完成提醒和远程审批；MarbleOS 进一步把任务、文件、工具和输出放进同一工作台。</p></div><div className="signal-box"><strong>降温与退出核心观察</strong><p>Agent Commerce 没有出现退款、售后或订单身份的新验证；AI 视频的真实可编辑时间线没有得到新的强信号；通用 Wrapper 继续数量多、有效差异少。</p></div><h2>本周 Top 10</h2>{items.map((x,i)=><section key={x.name}><h3>{i+1}. {x.name}</h3><p><strong>来源：</strong><a href={x.url} target="_blank" rel="noreferrer">{x.source}</a>　<strong>类别：</strong>{x.category}</p><p><strong>产品：</strong>{x.desc}</p><p><strong>为什么值得关注：</strong>{x.why}</p><p><strong>发布与讨论信号：</strong>{x.signal}</p></section>)}<h2>历史对比</h2><div className="signal-box"><strong>连续出现</strong><ul><li>Coding Agent 周边连续两周最密集，但从 Runtime 周边升级为治理控制面。</li><li>Context / Memory 继续从“存储更多”转向 Repo-owned、选择性加载与可审查。</li><li>Agent 监督从通知与审批，向任务、文件、输出可见的工作台演进。</li><li>Agent 安全从秘密隔离，扩展到逐次敏感数据授权。</li></ul></div><div className="signal-box"><strong>首次出现</strong><ul><li>生产 Agent 的持续评测、回归和自我改进闭环。</li><li>Skill 的企业级分发、版本、权限和运行证明。</li><li>MCP Server 的身份、计费、限流和密钥轮换。</li><li>企业 AI 使用与成本的统一 System of Record。</li></ul></div><h2>下周继续观察</h2><ul><li>Skill Registry 是否出现版本固定、加载证明和供应链安全机制。</li><li>Agent Eval 产品是否披露真实回归率、误报和人工介入成本。</li><li>Repo-owned Context 是否形成团队协作、过期清理和冲突处理。</li><li>Workspace-first 产品是否比 Chat-first 产品获得更高留存。</li><li>企业 AI Spend 产品是否能连接业务结果，而不只是统计 Token 和席位。</li></ul></article></main>}